# Use custom build commands
build: off

init:
  - ps: Write-Host "Initializing virtual machine ..."
  - ps: git --version

install:
  - ps: Write-Host "Installing requirements..."
  - ps: python --version
  - ps: python -m pip install pip --upgrade
  - ps: python -m pip install -r .\requirements.txt

build_script:
  - ps: Write-Host "Testing pyVersioning ..."
  - ps: pyVersioning yaml
