# Use custom build commands
build: off

image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\Python37"
    - PYTHON: "C:\Python38"

init:
  - ps: Write-Host "Initializing virtual machine ..."
  - ps: git --version

install:
  - ps: Write-Host "Installing requirements..."
  - SET PATH=%PYTHON%;%path%
  - ps: python --version
  - ps: python -m pip install pip --upgrade
  - ps: python -m pip install -r .\requirements.txt

build_script:
  - ps: Write-Host "Testing pyVersioning ..."
  - ps: pyVersioning yaml
